### ISSUE TITLE
Left precedence of pipeline

### ISSUE THREAD

**Issue by jridgewell** [js-choi/proposal-hack-pipes#12]
Spinning this out of https://github.com/js-choi/proposal-hack-pipes/issues/11:

> On the left, `|>` is as tight as assignment operators. This allows parsing `x = y |> z` as `x = (y |> z)`, and `x ? y : z |> w` as `(x ? y : z) |> w`.

That ternary example is super confusing, and it's different than how arrows are parsed:

```js
// arrow:
x ? y : z => w;

// parsed as
x ? y : (z => w);
```

The [spec](https://jschoi.org/21/es-hack-pipes/#sec-assignment-operators) seems to say arrows and pipelines would bind at the same level, so I'd think the ternary example would be `x ? y : (z |> w)`

When I load this into [AST explorer](https://astexplorer.net/#/gist/702ffe096551e7d13fb2724f96be83c1/47a2722522407be5b238684f526c4e97420d51ad), I actually get the same results for pipeline and arrow, but maybe that's just because babel hasn't fixed the right-associativity of the operator [yet](https://github.com/babel/babel/pull/13668).

/cc @nicolo-ribaudo

**Comment by js-choi** [comment]
Yeah, `x ? y : z |> w` does break parallelism with `x ? y : z => w`—because `x ? y : z` is an invalid left-hand side for `=>`, it does not group in the same way that `|>` would.

I’m not sure what the best way to tackle this would be. That’s a fundamental difference between the left-hand sides of `=>` and `|>`. (The right-hand sides’ grouping remains the same, as far as I can tell.)

That AST Explorer behavior is probably due to its using Babel 7.14, before Hack pipes were actually introduced.

**Comment by nicolo-ribaudo** [comment]
When trying to think about "what's confusing", always also consider the example with the syntax in the middle:
```js
a |> % ? b : c |> % + 1
```
Should it be `a |> (% ? b : c) |> % + 1` or `a |> (% ? b : (c |> % + 1)`?

On the other hand, `a ? b |> % + 1 : c |> % + 2` is _really_ confusing.

---

Fyi, I opened https://github.com/fkling/astexplorer/pull/599 for ASTExplorer.

**Comment by js-choi** [comment]
After more thought, I think we should require all conditionals to be parenthesized in pipe heads/bodies after all.

I’m thinking that the most desirable behavior might be to ban any any other assignment-level operation without parentheses as a pipe head or body. (The other assignment-level operations are `=>`, `=`, `+=`, etc., `?` `:`, and `yield`.) 

In contrast, pipe expressions would be allowed at any place in other assignment-level operations. So `x ? y : z |> w` would be parsed as `x ? y : (z |> w)`—parallelism with `=>` would be maintained.

I put a table with this behavior in https://github.com/js-choi/proposal-hack-pipes/issues/11#issuecomment-899935370. I plan to edit the explainer and spec soon.

**Comment by js-choi** [comment]
After 6c458b5, the left side of a `|>` PipeExpression is now ShortCircuitExpression, while its right side remains AssignmentExpression. The behavior should match that in https://github.com/js-choi/proposal-hack-pipes/issues/11#issuecomment-899935370. This should be less confusing and address this confusing mismatch with `=>`’s grouping. Thanks, @jridgewell, for pointing it out; let me know if you still have a concern.

<table>

<tr>
<td colspan=2><strong>Conditional then arrow/pipe</strong>

<tr>
<td><code>x ? y : z => w</code>
<td><code>x ? y : (z => w)</code>

<tr>
<td><code>x ? y : z |> %</code>
<td><code>x ? y : (z |> %)</code>

<tr>
<td colspan=2><strong>Arrow/pipe then conditional</strong>

<tr>
<td><code>w => x ? y : z</code>
<td><code>w => (x ? y : z)</code>

<tr>
<td><code>w |> % ? y : z</code>
<td>SyntaxError

<tr>
<td><code>w |> (% ? y : z)</code>
<td><code>w |> (% ? y : z)</code>

<tr>
<td><code>(w |> %) ? y : z</code>
<td><code>(w |> %) ? y : z</code>

</table>
