### ISSUE TITLE
Would be great to use named placeholder

### ISSUE THREAD

**Issue by pie6k** [js-choi/proposal-hack-pipes#16]
Eg. In some cases it might be way more readable if I can do

```
process.env
|> Object.keys(^)
|> filterUppercase(^keysList)
|> filterCamelCase(^upperKeys)
```

This allows me to express what is expected thing at given stage making it easier to read for fellow developer.

**Comment by js-choi** [comment]
Thanks for the issue!

We thought about named topics and played around with some syntaxes, such as `v |:foo> f(foo)`.

In the end, we decided to leave named topics to future proposals, making them out of scope of this proposal. 

(Pipes aren’t meant to replace variable assignment, after all; we’re keeping this simple.)

```js
const keysList = process.env |> Object.keys(^);
const upperKeys = filterUppercase(keysList);
filterCamelCase(upperKeys);
```

We’re leaving it as a possibility for future proposals—sorry if that’s disappointing, and thanks again for the issue. 👍

**Comment by tabatkins** [comment]
Note that pipeline is, in this respect, identical to method chaining:

```js
process.env
	.keys()
	.filterUppercase()
	.filterCamelCase();
```

The implicit subject of each call isn't named at any point there, either, but that seems to be broadly acceptable to the JS community, and method chaining remains a very popular syntax.

And, just like method chaining, you can always break the pipe and assign the result to a variable when that would aid in readability, as @js-choi's example shows off.
