### ISSUE TITLE
What if an expression containing a placeholder was just an alternative syntax for a unary function?

### ISSUE THREAD

**Issue by peterolson** [js-choi/proposal-hack-pipes#19]
What if, instead of having special rules about the placeholder only being allowed in a pipe body, an expression containing the placeholder could be an alternative syntax to a unary function in general?

That is, 

`foo(^, 0)` would just be syntactic sugar for `x => foo(x, 0)`?

Then there would be no real difference between Hack pipes and F# pipes,

**Comment by tabatkins** [comment]
That's the partial-application proposal from Ron Buckton. ^_^

Unfortunately it has two issues:

* it's still function-focused, and doesn't allow for anything that's not a function, at least not without a wrapper. Can't do `^[0]` or `^ + 1` or `^.method()`, etc. These sorts of expressions appear in real-world heavily-nested code all the time (see many of the examples in the README), and it would be unfortunate to leave them behind.
* it doesn't work with any JS features that pay attention to their nearest function wrapper, notably `await` (but also `yield`). The F#-style proposal had to have a special syntax rule allowing `await` as a bare keyword in a pipe body (like `promise |> await |> f`) to address this, and we'd have to add that back to do the same. I don't believe any pipe proposal is viable if it doesn't handle async stuff well.

**Comment by js-choi** [comment]
Thanks for taking the time to file this issue.

To add onto @TabAtkins’ comment, it also has a third problem: it would be a [garden-path grammar](https://en.wikipedia.org/wiki/Garden-path_sentence), which affects both human readers and computer parsers. We would lose the ability to tell, when reading from left to right, whether `f(veryLongBlockSpanning70Lines)` is an actual immediate function call or a function creation…until we search the entire `veryLongBlockSpanning70Lines` for even a single `^`. Lots of backtracking/lookahead is required to distinguish between these two meanings. Some people on the Committee understandably have pushed back against this.

It’s true (and has been brought up) that JavaScript *already* has some garden-path parsing, with arrow-function parameters being indistinguishable from parenthesized expressions until `=>` is reached.

But I would argue that we still want to minimize adding *more* garden-path grammar, for the sake of readability. (In addition, at least it’s easy for humans to skip ahead to the end of parenthesized expressions to check whether there’s an `=>` at the end—but `^` could appear *anywhere* in the `veryLongBlockSpanning70Lines`, *and* where it appears in the nesting would affect whether it affects the outer function call or some inner function call. (At least with [pipe functions `+>`](https://github.com/js-choi/proposal-hack-pipes/blob/main/README.md#hack-pipe-functions), there’s a `+>` at the front indicating that the following is function creation, not a function call, for humans and parsers reading left to right.)

Thanks for filing this issue!
