### ISSUE TITLE
Babel plugin?

### ISSUE THREAD

**Issue by mationai** [js-choi/proposal-hack-pipes#5]
Sorry if this is not the place to ask, but I don't know where else may be better. I don't think the Babel plugin exists yet as I couldn't find it. Is someone currently working on this?  EDIT: Is this something that wouldn't be out until it's in stage 1?  Is there an alpha version where I can try it out?

thank you.

**Comment by Pokute** [comment]
There's a Babel-plugin for Smart-style pipeline proposal, which I believe is a superset of Hack-style pipelines. The big difference is that you can use `'Foo' |> console.log` without adding `(#)`. You can try it out online [here](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAlmYAnApgWxWWBeGBDGbAPnxgGoYBGAbgChRJY8ATZwmACjwBoYAjAJSESBCnzr1w0GKggBXADY4YAbUrcATNwDMAXVowAPiQDEAOjR4ADl2GkAVDA0wBB4zHMAzOEpRJbxKQkAKyuRqZmqMxywCgcHPJovHhCgXhkibwADGHuCMjomFBuIqwcJrzarpKQIAooZgogAOYcsopQAtQwAPQ9VFlAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=stage-1%2Cstage-2&prettier=false&targets=&version=7.13.15&externalPlugins=).

There's also a [TypeScript playground](https://www.staging-typescript.org/play?target=99&ts=4.3.0-pr-43617-7&ssl=1&ssc=1&pln=29&pc=1#code/PTAEAUBsEME8HMBOB7ArgOwCagGbMaABLQDGA1gLQDOALrJAKagAOAlsw5K+g1aABY0azKgC4Q8VjX6oARgDoSyALbAAVlQol+yVsGYpmyKtEgV+pSmw5VgAKBBFofACqkpoAKrpoiWKAAxDBIaVmR0UABBZmYuEmhQ8NAqVBj8GlBpFFR4fkz+JgAfAD5i0ApkDkQE-HkHMBdYDgBlEkR2DPAAJVEBIRFxYElpOUUVYABZVjbjZBwaYEaWto79VEhIYAAWAGYANgBGAHY7OyV0WkyAeVAAXlAeAHcIFGVWKgYAHlp29HhigAUAMQvGQkAAbgwAJR3MoAbzsoGSDBoLlYygYaBoQJht2KiNACKRSIA5NBHtApAxMCTQCUyiCqGDIQBuAkAXwANKAAKwABj5ULZ7Khp3OlwY2mQDAI92csHQJFAAOYvXAr3eXzhmWQzRov3gvWg6H87LKhUJOr1BqNJtAIthhIJSOYzuJSJKoHJlIyAGI3e7Pb7QABqUC02lh-3uwOlUDisEMeSQZDwYWnSU6GUAmhXIVi8KXapYFQASXQGXuAOU0AAHr10KhlLIZbj8e6Jgl+PJi5gVADRTHiUHQAAqUA12sB4dxzvSeT64Jsuy9ssVgEAJkFdLjCcYydTbMz0sQAJ2Avzq+U5exW5h9NAx5lbKAA) which additionally supports the |>> operator.

**Comment by js-choi** [comment]
Sorry for the confusion. We're working on the Babel plugin in babel/babel#13191. We’ll update the readme when it’s released.

**Comment by js-choi** [comment]
The explainer was updated about the Babel plugin in 7a98c24837d8dd3bee3f6e2b29aa03dbf9be9c48. It is planned for Babel v7.15 and is being tracked in babel/babel#13191.
