### ISSUE TITLE
Misleading statement in the README

### ISSUE THREAD

**Issue by anatoliyarkhipov** [js-choi/proposal-hack-pipes#6]
The README states:
> The two pipe proposals just differ slightly on what the “magic” is, and thus on precisely how you spell your code when using |>.

That statement ignores the fact that there is a lot of libraries that developed their own `pipe`s despite the limitations of the language, with thousands developers using them already, that would greatly benefit from the minimal proposal, and would be thrown aboard with the Hack one. It seems quite important difference to me.

**Comment by js-choi** [comment]
Thanks for the feedback. I don’t think there’s much actionable here, but here are my thoughts:

The primary benefit of *any* pipe operator would be being able to **untangle deeply nested expressions** like `f(g(h(i(j(x)))))` into linear, left-to-right flows of data.

*Any* existing library would get this untangling benefit from *any* of the pipe-operator proposals. All three pipe-operator proposals allow for this untangling of nested expressions. It’s just a matter of which gets to be slightly more concise: unary function calls or everything else.

Existing libraries that use `pipe` functions that compose unary functions would still benefit from Hack pipes (and F# pipes), just as existing libraries that use a lot of n-ary function calls and method calls would benefit from F# pipes (and Hack pipes).

With Hack pipes, unary function calls require adding on an explicit `(%)` or whatever. This is a very similar tradeoff that would be made by F# pipes with requiring adding `x=>` onto n-ary function calls, method calls, arithmetic expressions, `yield` expressions, and any other kind of non-unary-function expression.

I wouldn’t say that F# pipes throw libraries that use n-ary function calls, method calls, arithmetic expressions, `yield` expressions, etc. overboard…just as I wouldn’t say that Hack pipes throw libraries that use unary function calls overboard.

@TabAtkins originally wrote that statement you quoted, and I still find it true. Neither proposal throws any kind of library overboard. It really is a small tradeoff in all cases, no matter the type of expression. Everyone would benefit from any sort of pipe operator, the primary benefit of which is universal: to untangle deeply nested expressions.

Thanks again for the feedback.
