### ISSUE TITLE
Grammar allows topic in some assignment targets

### ISSUE THREAD

**Issue by js-choi** [js-choi/proposal-hack-pipes#9]
@JLHwung raised a concern in https://github.com/babel/babel/pull/13536#issuecomment-880329810. To prevent cluttering up babel/babel#13536, I’m opening an issue here. The topic token is assumed to be `%` in this issue.

~~The current grammar does not correctly raise early errors for `x |> ((%) => {})` and `x |> (async (%) => {})`. This is because, inside of a PipeBody, `%` is hidden from the Contains operation—including in any CoverParenthesizedExpressionAndArrowParameterList that is within the PipeBody.~~

So, just like how the current grammar (correctly) allows `x |> ((%))`, so too does it (incorrectly) allow `x |> ((%) => {})`. In both cases, PipeBody contains a topic inside of two nested CoverParenthesizedExpressionAndArrowParameterLists.

@lightmare pointed to [AssignmentTargetType][] as a good place to prohibit the topic for these cases. This should also let expressions like `x |> %[y] = z`, `x |> y[%] = z`, and `x |> ((y = %) => {})` remain correctly valid.

(@JLHwung also said that the current grammar also does not correctly raise early errors for `x |> (% = 0)` and `x |> (% += 0)`. ~~However, I’m not sure if this is true.~~ [LeftHandSideExpression][] allows only NewExpression, CallExpression, and OptionalExpression, and ~~none of these expressions can result in an assignment to a topic reference~~.)

[AssignmentTargetType]: https://tc39.es/ecma262/#sec-static-semantics-assignmenttargettype
[LeftHandSideExpression]: https://tc39.es/ecma262/#prod-LeftHandSideExpression

**Comment by lightmare** [comment]
> so too does it (incorrectly) allow `x |> ((%) => {})`

I don't think it does. [ArrowParameters](https://tc39.es/ecma262/#prod-ArrowParameters) only allow `BindingIdentifier`, which `%` is not.

> [LeftHandSideExpression](https://tc39.es/ecma262/#prod-LeftHandSideExpression) allows only NewExpression

`NewExpression` > `MemberExpression` > `PrimaryExpression` > `%`

**Comment by js-choi** [comment]
@lightmare: Thanks for the correction; I was mistaken. The grammar currently correctly prohibits `x |> ((%) => {})` (`(%)` matches neither BindingIdentifier nor `(` UniqueFormalParameters `)`) but incorrectly allows `x |> (% = 0)`. Either way, we should add a restriction to AssignmentTargetType as you suggested.
